name: Node CI
on:
  push:
env:
  HUSKY: 0
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
jobs:
  test:
    name: "Test (Node.js v${{ matrix.node-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14, 16, 18 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn run -T node+deps build
      - run: yarn run -T node lint
      - run: yarn run -T node test

  # - label: '[Node] Lint + Test'
  #   key: analytics-node-test
  #   agents:
  #     queue: v1
  #   commands:
  #     - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
  #     - echo "--- Install dependencies"
  #     - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 HUSKY=0 yarn install --immutable
  #     - echo "--- Build bundles"
  #     - yarn run -T node+deps build
  #     - echo "+++ Run tests"
  #     - yarn run -T node lint
  #     - yarn run -T node test
  #   plugins:
  #     - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
  #         key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
  #         paths: ['.yarn/cache/']

  # - label: '[Node] Integration Tests :perfection:'
  #   key: analytics-node-lint-test
  #   agents:
  #     queue: v1
  #   commands:
  #     - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
  #     - echo "--- Install dependencies"
  #     - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 HUSKY=0 yarn install --immutable
  #     - echo "--- Build bundles"
  #     - yarn turbo run --filter=node-integration-tests build
  #     - echo "+++ Run tests"
  #     - yarn turbo run --filter=node-integration-tests lint
  #     - yarn turbo run --filter=node-integration-tests test
  #   retry:
  #     automatic:
  #       - exit_status: '*'
  #         limit: 2
  #   plugins:
  #     - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
  #         key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
  #         paths: ['.yarn/cache/']
